 	# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with: 
        java-version: '8'
    - uses: actions/upload-artifact@v2
      with:
        path: binaries_to_upload/*.jar
    - name: Veracode Upload and Scan Action Step
      uses: ./ # Uses an action in the root directory
      id: upload_and_scan
      with:
        appname: 'Components'
        version: '${{ github.run_id }}'
        filepath: 'binaries_to_upload/*.jar'
        vid: '55da4db3450e3fdfa8021a491c2eb0a4'
        vkey: '6893bc44e5991ae48452cc7161eb0fc7666bce200473aa48182cf1bd66428a3e651649ad64547e194fbb27ebb4fb6de0a59a0c5df1a26c3a606b4410fdc5bdc2'
        createsandbox: true
        sandboxname: 'GITTEST'
        scantimeout: 60
        criticality: 'Medium'

